services:
  app:
    
    container_name: pokenow_app
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
         - NEXT_PUBLIC_POKE_API_URL=${NEXT_PUBLIC_POKE_API_URL:-https://pokeapi.co/api/v2/}
    volumes:
      - ./data:/app/data
  
    command: ["pnpm", "start"] 
